/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionPanel: typeof import('./src/components/ActionPanel.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    GameTable: typeof import('./src/components/GameTable.vue')['default']
    GameTimer: typeof import('./src/components/GameTimer.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    PlayerAvatar: typeof import('./src/components/PlayerAvatar.vue')['default']
    PlayerHand: typeof import('./src/components/PlayerHand.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
