version: '3.8'

services:
  # MariaDB数据库服务
  database:
    image: mariadb:latest
    container_name: guandan_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: guandan_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  # 后端服务 (可选，可以通过docker-compose统一管理)
  backend:
    build: ./backend
    container_name: guandan_backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=guandan_db
      - DB_USER=user
      - DB_PASSWORD=password
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge